// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter address of method ReadManaged is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ProcessFacade.ReadManaged(HackF5.UnitySpy.Detail.TypeInfo,System.UInt32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "SA1513:Closing brace should be followed by blank line", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ProcessFacade.ReadManaged(HackF5.UnitySpy.Detail.TypeInfo,System.UInt32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter type of method ReadManagedStructInstance is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ProcessFacade.ReadManagedStructInstance(HackF5.UnitySpy.Detail.TypeInfo,System.UInt32)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.ITypeInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter address of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.AssemblyImage.#ctor(HackF5.UnitySpy.Detail.ProcessFacade,System.UInt32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter address of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ManagedObjectInstance.#ctor(HackF5.UnitySpy.Detail.AssemblyImage,System.UInt32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter type of method ReadManagedArray is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ProcessFacade.ReadManagedArray(HackF5.UnitySpy.Detail.TypeInfo,System.UInt32)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter type of method ReadManagedClassInstance is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ProcessFacade.ReadManagedClassInstance(HackF5.UnitySpy.Detail.TypeInfo,System.UInt32)~HackF5.UnitySpy.Detail.ManagedClassInstance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.IFieldDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.IMemoryObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.ITypeDefinition")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.IManagedObjectInstance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1040:Avoid empty interfaces", Justification = "<Pending>", Scope = "type", Target = "~T:HackF5.UnitySpy.IAssemblyImage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'definitionAddress'.", Justification = "<Pending>", Scope = "member", Target = "~F:HackF5.UnitySpy.Detail.ManagedClassInstance.definitionAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'vtable'.", Justification = "<Pending>", Scope = "member", Target = "~F:HackF5.UnitySpy.Detail.ManagedClassInstance.vtable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter typeDefinition of method .ctor is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Detail.ManagedStructInstance.#ctor(HackF5.UnitySpy.Detail.TypeDefinition,System.UInt32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter process of method GetProcessModulePointers is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:HackF5.UnitySpy.Util.Native.GetProcessModulePointers(HackF5.UnitySpy.Detail.ProcessFacade)~System.IntPtr[]")]