// <auto-generated>
namespace HackF5.UnitySpy.Detail
{
    using System.ComponentModel;

    /// <summary>
    /// Represents the type of an object in managed memory.
    /// See: MonoTypeEnum in https://github.com/Unity-Technologies/mono/blob/unity-master/mono/metadata/blob.h.
    /// </summary>
    public enum TypeCode
    {
        [Description("int")]
        I = 0x18,

        [Description("uint")]
        U = 0x19,
        FNPTR = 0x1b,       /* arg: full method signature */
        OBJECT = 0x1c,
        SZARRAY = 0x1d,     /* 0-based one-dim-array */
        MVAR = 0x1e,        /* number */
        CMOD_REQD = 0x1f,   /* arg: typedef or typeref token */
        CMOD_OPT = 0x20,    /* optional arg: typedef or typref token */
        INTERNAL = 0x21,    /* CLR internal type */
        MODIFIER = 0x40,    /* Or with the following types */
        SENTINEL = 0x41,    /* Sentinel for varargs method signature */
        PINNED = 0x45,      /* Local var that points to pinned object */
        ENUM = 0x55         /* an enumeration */
    }
}