// <auto-generated>
namespace HackF5.UnitySpy.Detail
{
    /// <summary>
    /// Represents the type of an object in managed memory.
    /// See: MonoTypeEnum in https://github.com/Unity-Technologies/mono/blob/unity-master/mono/metadata/blob.h.
    /// </summary>
    public enum TypeCode
    {
        END = 0x00,         /* End of List */
        VOID = 0x01,
        BOOLEAN = 0x02,
        CHAR = 0x03,
        I1 = 0x04,
        U1 = 0x05,
        I2 = 0x06,
        U2 = 0x07,
        I4 = 0x08,
        U4 = 0x09,
        I8 = 0x0a,
        U8 = 0x0b,
        R4 = 0x0c,
        R8 = 0x0d,
        STRING = 0x0e,
        PTR = 0x0f,         /* arg: <type> token */
        BYREF = 0x10,       /* arg: <type> token */
        VALUETYPE = 0x11,   /* arg: <type> token */
        CLASS = 0x12,       /* arg: <type> token */
        VAR = 0x13,         /* number */
        ARRAY = 0x14,       /* type, rank, boundsCount, bound1, loCount, lo1 */
        GENERICINST = 0x15, /* <type> <type-arg-count> <type-1> \x{2026} <type-n> */
        TYPEDBYREF = 0x16,
        I = 0x18,
        U = 0x19,
        FNPTR = 0x1b,       /* arg: full method signature */
        OBJECT = 0x1c,
        SZARRAY = 0x1d,     /* 0-based one-dim-array */
        MVAR = 0x1e,        /* number */
        CMOD_REQD = 0x1f,   /* arg: typedef or typeref token */
        CMOD_OPT = 0x20,    /* optional arg: typedef or typref token */
        INTERNAL = 0x21,    /* CLR internal type */
        MODIFIER = 0x40,    /* Or with the following types */
        SENTINEL = 0x41,    /* Sentinel for varargs method signature */
        PINNED = 0x45,      /* Local var that points to pinned object */
        ENUM = 0x55         /* an enumeration */
    }
}